# Generated by Django 4.1.13 on 2024-11-13 04:39

import bson.objectid
from django.db import migrations, models
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='id', default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_original', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_sample', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'db_table': 'files',
            },
        ),
    ]
