version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "mkdir -p /app/server/files && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./server/files:/app/server/files
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - davi-network
    restart: unless-stopped

  db:
    image: mongo:latest
    container_name: davi-apis-db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=daviapisdb
    networks:
      - davi-network
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local

networks:
  davi-network:
    driver: bridge