name: Deploy Django to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Change this to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2
      env:
        AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
        AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        # PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        echo "$AWS_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_EC2_USER@$AWS_EC2_HOST << 'EOF'
          cd $PROJECT_PATH
          git pull origin main  # Ensure you are on the correct branch
          source venv/bin/activate  # Activate your virtual environment
          pip install -r requirements.txt  # Install any new dependencies
          python manage.py migrate  # Run migrations
          python manage.py collectstatic --noinput  # Collect static files
          sudo systemctl restart nginx  # Restart the web server
        EOF
