name: Deploy to EC2

on:
  push:
    branches:
      - production2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            # Install Python 3.12 if not already installed
            if ! python3.12 --version &>/dev/null; then
              sudo add-apt-repository ppa:deadsnakes/ppa -y
              sudo apt update
              sudo apt install -y python3.12 python3.12-venv python3.12-dev
            fi

            # Navigate to the deployment directory
            cd /home/${{ secrets.AWS_EC2_USER }}

            # Extract and deploy the app
            rm -rf app
            mkdir app
            tar -xzf app.tar.gz -C app
            rm -f app.tar.gz

            # Set up virtual environment
            python3.12 -m venv env
            source env/bin/activate

            # Install dependencies
            pip install --upgrade pip
            pip install -r app/requirements.txt

            # Apply migrations and start the app
            python app/manage.py migrate --noinput
            nohup gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 4 &
          EOF
