name: Deploy to EC2

on:
  push:
    branches:
      - main  # Deploy only when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to access EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Verify docker-compose.yml exists in the root
      - name: Verify docker-compose.yml Exists
        run: |
          if [ ! -f docker-compose.yml ]; then
            echo "Error: docker-compose.yml not found in the root directory."
            exit 1
          fi

      # Step 4: Compress project files for transfer
      - name: Compress files for transfer
        run: |
          tar -czf app.tar.gz --exclude='.git' --exclude='.github' .

      # Step 5: Copy compressed file to EC2
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no app.tar.gz ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.AWS_EC2_USER }}/

      # Step 6: Deploy on EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.AWS_EC2_USER }}
            rm -rf app  # Remove old app directory to avoid conflicts
            mkdir app
            tar -xzf app.tar.gz -C app  # Extract files into app directory
            cd app

            # Check if Docker Compose is installed, install if missing
            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose not found, installing..."
              sudo apt update && sudo apt install -y docker-compose
            fi

            # Deploy with Docker Compose
            docker-compose down  # Stop existing containers
            docker-compose up --build -d  # Rebuild and run in detached mode
          EOF
