name: Deploy to EC2

on:
  push:
    branches:
      - main  # Deploy only when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to access EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Verify docker-compose.yml exists in the root
      - name: Verify docker-compose.yml Exists
        run: |
          if [ ! -f docker-compose.yml ]; then
            echo "Error: docker-compose.yml not found in the root directory."
            exit 1
          fi

      # Step 4: Copy project files to a temporary directory and compress
      - name: Compress files for transfer
        run: |
          # Create a temp directory and copy all project files into it
          mkdir -p temp_dir
          rsync -a --exclude='.git' --exclude='.github' . temp_dir/
          
          # Compress the temp directory into app.tar.gz
          tar -czf app.tar.gz -C temp_dir .          
          # Clean up temp directory
          rm -rf temp_dir

      # Step 5: Copy compressed file to EC2
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no app.tar.gz ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.AWS_EC2_USER }}/

      # Step 6: Deploy on EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.AWS_EC2_USER }}
            rm -rf app  # Remove old app directory to avoid conflicts
            mkdir app
            tar -xzf app.tar.gz -C app  # Extract files into app directory
            cd app

            # Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found, installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo usermod -aG docker $USER
              newgrp docker
            fi

            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose not found, installing..."
              sudo apt update && sudo apt install -y docker-compose
            fi

            # Ensure required directories and permissions
            mkdir -p /home/${{ secrets.AWS_EC2_USER }}/app/server/files
            chmod -R 777 /home/${{ secrets.AWS_EC2_USER }}/app/server/files  # Use 777 for testing

            # Deploy with Docker Compose
            docker-compose down  # Stop existing containers
            docker-compose up --build -d  # Rebuild and run in detached mode
          EOF
